using System.Linq;
using Grynwald.ChangeLog.Configuration;
using Grynwald.ChangeLog.Model;
using Grynwald.MarkdownGenerator;
using NuGet.Versioning;

namespace Grynwald.ChangeLog.Templates.GitHubRelease
{
    internal class GitHubReleaseTemplate : MarkdownBaseTemplate
    {
        /// <inheritdoc />
        protected override MdSerializationOptions SerializationOptions => MdSerializationOptions.Default;


        public GitHubReleaseTemplate(ChangeLogConfiguration configuration) : base(configuration)
        { }


        /// <inheritdoc />
        protected override MdDocument GetChangeLogDocument(ApplicationChangeLog changeLog)
        {
            if (changeLog.ChangeLogs.Count() > 1)
                throw new TemplateExecutionException("The GitHub Release template cannot render change logs that contain multiple versions");

            if (!changeLog.ChangeLogs.Any())
                return new MdDocument(GetEmptyBlock());

            // Return changes for only a single change, omit surrounding headers
            return new MdDocument(
                GetVersionContentBlock(changeLog.Single())
            );
        }

        /// <inheritdoc />
        protected override MdBlock GetSummaryListHeaderBlock(string listTitle)
        {
            // in GitHub releases, the top heading is <h2> because higher,            
            return new MdHeading(2, listTitle);
        }

        /// <inheritdoc />
        protected override MdBlock GetBreakingChangesListHeaderBlock(VersionInfo versionInfo)
        {
            // in GitHub releases, the top heading is <h2> because higher,
            return new MdHeading(2, "Breaking Changes");
        }

        /// <inheritdoc />
        protected override MdBlock GetDetailSectionHeaderBlock(NuGetVersion version)
        {
            // in GitHub releases, the top heading is <h2> because higher,
            return new MdHeading(2, "Details");
        }

        /// <inheritdoc />
        protected override MdBlock GetEntryDetailHeaderBlock(ChangeLogEntry entry)
        {
            // in GitHub releases, the top heading is <h2> because higher,
            // => the header for individual entries is the level of the "details" header + 1 => 3
            return new MdHeading(3, GetSummaryText(entry));
        }

        /// <inheritdoc />
        protected override string GetHtmlHeadingId(ChangeLogEntry entry)
        {
            // use default header ids generated by GitHub instead of setting a header explicitly
            return new MdHeading(1, GetSummaryText(entry)).Anchor ?? "";
        }
    }
}
